---
# file: playbook.yml
# Shortcut to run install tasks on the localhost without setting up an inventory.
- hosts: localhost
  connection: local
  vars:
    galaxy_config_style: yaml
    galaxy_layout: legacy-improved
    galaxy_server_dir: /galaxy/server
    galaxy_requirements_file: "{{ galaxy_server_dir }}/lib/galaxy/dependencies/k8s-requirements.txt"
    galaxy_virtualenv_command: /usr/bin/python3 -m virtualenv
    galaxy_virtualenv_python: python3
    pip_extra_args: "--no-cache-dir --compile"
    galaxy_manage_database: false
    galaxy_manage_clone: false
    galaxy_manage_existing: true
    galaxy_client_make_target: client-production
    galaxy_config_files:
      - src: files/welcome.html
        dest: "{{ galaxy_server_dir }}/static/welcome.html"
      - src: files/k8s-requirements.txt
        dest: "{{ galaxy_server_dir }}/lib/galaxy/dependencies/k8s-requirements.txt"

    galaxy_config:
      gravity:
        gunicorn:
          bind: 0.0.0.0:8080
      uwsgi: {}
  tasks:
  - name: Run the galaxy role
    include_role:
      name: galaxyproject.galaxy
    tags: galaxy_build_client
